name: topo-seer
version: 0.1.0.0
license: MPL-2.0
license-file: LICENSE
author: You
maintainer: you@example.com
category: Terrain
synopsis: SDL app for terrain generation

library:
  source-dirs: src
  exposed-modules:
    - Actor.Data
    - Actor.Log
    - Actor.Render
    - Actor.SnapshotReceiver
    - Actor.Terrain
    - Actor.TerrainCacheWorker
    - Actor.UiActions
    - Actor.UiActions.Command
    - Actor.UiActions.Protocol
    - Actor.UiActions.Terrain
    - Actor.UI
    - Actor.AtlasCache
    - Actor.AtlasManager
    - Actor.AtlasResult
    - Actor.AtlasResultBroker
    - Actor.AtlasScheduleBroker
    - Actor.AtlasScheduler
    - Actor.AtlasWorker
    - Actor.TerrainCacheBroker
    - Seer
    - Seer.App
    - Seer.Config
    - Seer.Config.Runtime
    - Seer.Config.SliderSpec
    - Seer.Config.Snapshot
    - Seer.Config.Snapshot.Types
    - Seer.Draw
    - Seer.Draw.Dialog
    - Seer.Input
    - Seer.System
    - Seer.System.ThreadPriority
    - Seer.Input.ConfigScroll
    - Seer.Input.Modal
    - Seer.Input.Router
    - Seer.Input.Seed
    - Seer.Input.ViewControls
    - Seer.Render
    - Seer.Render.Atlas
    - Seer.Render.Frame
    - Seer.Render.Terrain
    - Seer.Render.Ui
    - Seer.World.Persist
    - Seer.World.Persist.Types
    - UI.Font
    - UI.Layout
    - UI.HexPick
    - UI.TerrainAtlas
    - UI.TerrainCache
    - UI.TerrainRender
    - UI.RiverRender
    - UI.Widgets
    - UI.WidgetsDraw
    - UI.WidgetTree
  dependencies:
    - aeson
    - base >=4.18 && <5
    - bytestring
    - containers
    - directory
    - filepath
    - stm
    - linear
    - vector
    - topo
    - hyperspace
    - text
    - time
    - random
    - sdl2
    - sdl2-ttf

executables:
  topo-seer:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -O2
      - -Wall
      - -threaded
      - -rtsopts
      - "-with-rtsopts=-N"
    dependencies:
      - base
      - topo-seer

tests:
  topo-seer-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - aeson
      - base
      - bytestring
      - containers
      - directory
      - filepath
      - QuickCheck
      - linear
      - time
      - topo
      - topo-seer
      - hspec
      - hyperspace
      - text
      - vector
