resolver: lts-24.2
packages:
  - topo
  - topo-seer
extra-deps:
  - git: https://github.com/Sornaensis/hyperspace
    commit: 4303126429a28d3ffd6fe2a67770d37ede3b08a7 # 0.1-testing
  - git: https://github.com/Sornaensis/sdl2
    commit: 74938f9f3bfe2d1e2767ce8166b6d543960250ce
  - git: https://github.com/Sornaensis/sdl2-ttf
    commit: 63cb3f1891778655e248d24337d7ba0e17e8f4d1

flags:
  sdl2:
    pkgconfig: false
  sdl2-ttf:
    pkgconfig: false
