module Seer.Config.SliderId
  ( SliderId(..)
  ) where

data SliderId
  = SliderGenScale
  | SliderGenCoordScale
  | SliderGenOffsetX
  | SliderGenOffsetY
  | SliderGenFrequency
  | SliderGenOctaves
  | SliderGenLacunarity
  | SliderGenGain
  | SliderGenWarpScale
  | SliderGenWarpStrength
  | SliderExtentX
  | SliderExtentY
  | SliderEdgeNorth
  | SliderEdgeSouth
  | SliderEdgeEast
  | SliderEdgeWest
  | SliderEdgeFalloff
  | SliderPlateSize
  | SliderUplift
  | SliderRiftDepth
  | SliderDetailScale
  | SliderPlateSpeed
  | SliderBoundarySharpness
  | SliderBoundaryNoiseScale
  | SliderBoundaryNoiseStrength
  | SliderBoundaryWarpOctaves
  | SliderBoundaryWarpLacunarity
  | SliderBoundaryWarpGain
  | SliderPlateMergeScale
  | SliderPlateMergeBias
  | SliderPlateDetailScale
  | SliderPlateDetailStrength
  | SliderPlateRidgeStrength
  | SliderPlateHeightBase
  | SliderPlateHeightVariance
  | SliderPlateHardnessBase
  | SliderPlateHardnessVariance
  | SliderTrenchDepth
  | SliderRidgeHeight
  | SliderPlateBiasStrength
  | SliderPlateBiasCenter
  | SliderPlateBiasEdge
  | SliderPlateBiasNorth
  | SliderPlateBiasSouth
  | SliderTfcCliffSlope
  | SliderTfcMountainSlope
  | SliderTfcMountainRelief
  | SliderTfcHillSlope
  | SliderTfcRollingSlope
  | SliderValleyCurvature
  | SliderTfcElevGradient
  | SliderTfcPlateauMaxRelief2Ring
  | SliderTfcPlateauMaxMicroRelief
  | SliderTfcRollingNearFactor
  | SliderRockElevationThreshold
  | SliderRockHardnessThreshold
  | SliderRockHardnessSecondary
  | SliderPlanetRadius
  | SliderAxialTilt
  | SliderInsolation
  | SliderOccWarmScale
  | SliderOccColdScale
  | SliderOccLatPeakDeg
  | SliderOccLatWidthDeg
  | SliderWaterLevel
  | SliderOrographicLift
  | SliderRainShadowLoss
  | SliderWindDiffuse
  | SliderEquatorTemp
  | SliderPoleTemp
  | SliderLapseRate
  | SliderWindIterations
  | SliderMoistureIterations
  | SliderBoundaryMotionTemp
  | SliderBoundaryMotionPrecip
  | SliderSliceLatCenter
  | SliderSliceLonCenter
  | SliderLatitudeExponent
  | SliderPlateHeightCooling
  | SliderTempNoiseScale
  | SliderOceanModeration
  | SliderOceanModerateTemp
  | SliderAlbedoSensitivity
  | SliderAlbedoReference
  | SliderMoistAdvect
  | SliderMoistLocal
  | SliderMoistWindEvapScale
  | SliderMoistEvapNoiseScale
  | SliderMoistBareEvapFrac
  | SliderMoistVegTranspFrac
  | SliderMoistWindETScale
  | SliderMoistCondensationRate
  | SliderMoistRecycleRate
  | SliderMoistITCZStrength
  | SliderMoistITCZWidth
  | SliderOrographicScale
  | SliderOrographicStep
  | SliderCoastalIterations
  | SliderCoastalDiffuse
  | SliderCoastalMoistureBoost
  | SliderWindBeltStrength
  | SliderWindBeltHarmonics
  | SliderWindBeltBase
  | SliderWindBeltRange
  | SliderWindBeltSpeedScale
  | SliderBndLandRange
  | SliderPiedmontSmooth
  | SliderPiedmontSlopeMin
  | SliderPiedmontSlopeMax
  | SliderWindCoriolisDeflection
  | SliderMoistMinVegFloor
  | SliderWeatherTick
  | SliderWeatherPhase
  | SliderWeatherAmplitude
  | SliderSeasonCycleLength
  | SliderJitterAmplitude
  | SliderPressureBase
  | SliderPressureTempScale
  | SliderPressureCoriolisScale
  | SliderSeasonalBase
  | SliderSeasonalRange
  | SliderHumidityNoiseScale
  | SliderPrecipNoiseScale
  | SliderWeatherITCZWidth
  | SliderWeatherITCZPrecipBoost
  | SliderPressureHumidityScale
  | SliderPressureGradientWindScale
  | SliderWindNoiseScale
  | SliderITCZMigrationScale
  | SliderCloudRHExponent
  | SliderCloudAlbedoEffect
  | SliderCloudPrecipBoost
  | SliderVegBase
  | SliderVegBoost
  | SliderVegTempWeight
  | SliderVegPrecipWeight
  | SliderBtCoastalBand
  | SliderBtSnowMaxTemp
  | SliderBtAlpineMaxTemp
  | SliderBtIceCapTemp
  | SliderBtMontaneMaxTemp
  | SliderBtMontanePrecip
  | SliderBtCliffSlope
  | SliderBtValleyMoisture
  | SliderBtDepressionMoisture
  | SliderBtPrecipWeight
  | SliderVbcTempMin
  | SliderVbcTempRange
  | SliderVbcFertilityBoost
  | SliderVbcAlbedoBase
  | SliderVbcAlbedoBare
  | SliderVbcAlbedoVeg
  | SliderVbcOceanAlbedo
  | SliderVbcIceAlbedo
  | SliderBiomeSmoothing
  | SliderVolcanicAshBoost
  | SliderVolcanicLavaPenalty
  | SliderBiomeFeedbackBlend
  | SliderErosionHydraulic
  | SliderErosionThermal
  | SliderErosionRainRate
  | SliderErosionTalus
  | SliderErosionMaxDrop
  | SliderErosionHydDeposit
  | SliderErosionDepositSlope
  | SliderErosionThermDeposit
  | SliderErosionCoastZone
  | SliderErosionCoastStrength
  | SliderErosionCoastIter
  | SliderHypsometryEnabled
  | SliderHypsometryLowlandExp
  | SliderHypsometryHighlandExp
  | SliderHypsometryPlateauBreak
  | SliderHypsometryOceanExp
  | SliderHypsometryCoastalRampWidth
  | SliderHypsometryCoastalRampStr
  | SliderGlacierSnowTemp
  | SliderGlacierSnowRange
  | SliderGlacierMeltTemp
  | SliderGlacierMeltRate
  | SliderGlacierAccumScale
  | SliderGlacierFlowIters
  | SliderGlacierFlowRate
  | SliderGlacierErosionScale
  | SliderGlacierCarveScale
  | SliderGlacierDepositScale
  | SliderVentDensity
  | SliderVentThreshold
  | SliderHotspotScale
  | SliderHotspotThreshold
  | SliderMagmaRecharge
  | SliderLavaScale
  | SliderAshScale
  | SliderVolcanicDepositScale
  | SliderSoilMoistureThreshold
  | SliderSoilHardnessThreshold
  | SliderSoilFertilityMoistWeight
  | SliderSoilFertilityDepthWeight
  | SliderSinkBreachDepth
  | SliderStreamPowerMaxErosion
  | SliderRiverCarveMaxDepth
  | SliderCoastalErodeStrength
  | SliderHydroHardnessWeight
  | SliderMinLakeSize
  | SliderInlandSeaMinSize
  | SliderRoughnessScale
  | SliderHexSizeKm
  deriving (Eq, Ord, Show, Enum, Bounded)
