module UI.WidgetId
  ( WidgetId(..)
  ) where

import Data.Text (Text)

data WidgetId
  = WidgetGenerate
  | WidgetLeftToggle
  | WidgetLeftTabTopo
  | WidgetLeftTabView
  | WidgetSeedValue
  | WidgetSeedRandom
  | WidgetChunkMinus
  | WidgetChunkPlus
  | WidgetConfigToggle
  | WidgetConfigTabTerrain
  | WidgetConfigTabPlanet
  | WidgetConfigTabClimate
  | WidgetConfigTabWeather
  | WidgetConfigTabBiome
  | WidgetConfigTabErosion
  | WidgetConfigTabPipeline
  | WidgetConfigPresetSave
  | WidgetConfigPresetLoad
  | WidgetConfigReset
  | WidgetConfigRevert
  | WidgetConfigWaterMinus
  | WidgetConfigWaterPlus
  | WidgetConfigOrographicLiftMinus
  | WidgetConfigOrographicLiftPlus
  | WidgetConfigRainShadowLossMinus
  | WidgetConfigRainShadowLossPlus
  | WidgetConfigWindDiffuseMinus
  | WidgetConfigWindDiffusePlus
  | WidgetConfigEquatorTempMinus
  | WidgetConfigEquatorTempPlus
  | WidgetConfigPoleTempMinus
  | WidgetConfigPoleTempPlus
  | WidgetConfigLapseRateMinus
  | WidgetConfigLapseRatePlus
  | WidgetConfigWindIterationsMinus
  | WidgetConfigWindIterationsPlus
  | WidgetConfigMoistureIterationsMinus
  | WidgetConfigMoistureIterationsPlus
  | WidgetConfigWeatherTickMinus
  | WidgetConfigWeatherTickPlus
  | WidgetConfigWeatherPhaseMinus
  | WidgetConfigWeatherPhasePlus
  | WidgetConfigWeatherAmplitudeMinus
  | WidgetConfigWeatherAmplitudePlus
  | WidgetConfigSeasonCycleLengthMinus
  | WidgetConfigSeasonCycleLengthPlus
  | WidgetConfigJitterAmplitudeMinus
  | WidgetConfigJitterAmplitudePlus
  | WidgetConfigPressureBaseMinus
  | WidgetConfigPressureBasePlus
  | WidgetConfigPressureTempScaleMinus
  | WidgetConfigPressureTempScalePlus
  | WidgetConfigPressureCoriolisScaleMinus
  | WidgetConfigPressureCoriolisScalePlus
  | WidgetConfigSeasonalBaseMinus
  | WidgetConfigSeasonalBasePlus
  | WidgetConfigSeasonalRangeMinus
  | WidgetConfigSeasonalRangePlus
  | WidgetConfigHumidityNoiseScaleMinus
  | WidgetConfigHumidityNoiseScalePlus
  | WidgetConfigPrecipNoiseScaleMinus
  | WidgetConfigPrecipNoiseScalePlus
  | WidgetConfigWeatherITCZWidthMinus
  | WidgetConfigWeatherITCZWidthPlus
  | WidgetConfigWeatherITCZPrecipBoostMinus
  | WidgetConfigWeatherITCZPrecipBoostPlus
  | WidgetConfigPressureHumidityScaleMinus
  | WidgetConfigPressureHumidityScalePlus
  | WidgetConfigPressureGradientWindScaleMinus
  | WidgetConfigPressureGradientWindScalePlus
  | WidgetConfigWindNoiseScaleMinus
  | WidgetConfigWindNoiseScalePlus
  | WidgetConfigITCZMigrationScaleMinus
  | WidgetConfigITCZMigrationScalePlus
  | WidgetConfigCloudRHExponentMinus
  | WidgetConfigCloudRHExponentPlus
  | WidgetConfigCloudAlbedoEffectMinus
  | WidgetConfigCloudAlbedoEffectPlus
  | WidgetConfigCloudPrecipBoostMinus
  | WidgetConfigCloudPrecipBoostPlus
  | WidgetConfigVegBaseMinus
  | WidgetConfigVegBasePlus
  | WidgetConfigVegBoostMinus
  | WidgetConfigVegBoostPlus
  | WidgetConfigVegTempWeightMinus
  | WidgetConfigVegTempWeightPlus
  | WidgetConfigVegPrecipWeightMinus
  | WidgetConfigVegPrecipWeightPlus
  | WidgetConfigBtCoastalBandMinus
  | WidgetConfigBtCoastalBandPlus
  | WidgetConfigBtSnowMaxTempMinus
  | WidgetConfigBtSnowMaxTempPlus
  | WidgetConfigBtAlpineMaxTempMinus
  | WidgetConfigBtAlpineMaxTempPlus
  | WidgetConfigBtIceCapTempMinus
  | WidgetConfigBtIceCapTempPlus
  | WidgetConfigBtMontaneMaxTempMinus
  | WidgetConfigBtMontaneMaxTempPlus
  | WidgetConfigBtMontanePrecipMinus
  | WidgetConfigBtMontanePrecipPlus
  | WidgetConfigBtCliffSlopeMinus
  | WidgetConfigBtCliffSlopePlus
  | WidgetConfigBtValleyMoistureMinus
  | WidgetConfigBtValleyMoisturePlus
  | WidgetConfigBtDepressionMoistureMinus
  | WidgetConfigBtDepressionMoisturePlus
  | WidgetConfigBtPrecipWeightMinus
  | WidgetConfigBtPrecipWeightPlus
  | WidgetConfigVbcTempMinMinus
  | WidgetConfigVbcTempMinPlus
  | WidgetConfigVbcTempRangeMinus
  | WidgetConfigVbcTempRangePlus
  | WidgetConfigVbcFertilityBoostMinus
  | WidgetConfigVbcFertilityBoostPlus
  | WidgetConfigVbcAlbedoBaseMinus
  | WidgetConfigVbcAlbedoBasePlus
  | WidgetConfigVbcAlbedoBareMinus
  | WidgetConfigVbcAlbedoBarePlus
  | WidgetConfigVbcAlbedoVegMinus
  | WidgetConfigVbcAlbedoVegPlus
  | WidgetConfigVbcOceanAlbedoMinus
  | WidgetConfigVbcOceanAlbedoPlus
  | WidgetConfigVbcIceAlbedoMinus
  | WidgetConfigVbcIceAlbedoPlus
  | WidgetConfigBiomeSmoothingMinus
  | WidgetConfigBiomeSmoothingPlus
  | WidgetConfigVolcanicAshBoostMinus
  | WidgetConfigVolcanicAshBoostPlus
  | WidgetConfigVolcanicLavaPenaltyMinus
  | WidgetConfigVolcanicLavaPenaltyPlus
  | WidgetConfigBiomeFeedbackBlendMinus
  | WidgetConfigBiomeFeedbackBlendPlus
  | WidgetConfigBoundaryMotionTempMinus
  | WidgetConfigBoundaryMotionTempPlus
  | WidgetConfigBoundaryMotionPrecipMinus
  | WidgetConfigBoundaryMotionPrecipPlus
  | WidgetConfigPlanetRadiusMinus
  | WidgetConfigPlanetRadiusPlus
  | WidgetConfigAxialTiltMinus
  | WidgetConfigAxialTiltPlus
  | WidgetConfigInsolationMinus
  | WidgetConfigInsolationPlus
  | WidgetConfigOccWarmScaleMinus
  | WidgetConfigOccWarmScalePlus
  | WidgetConfigOccColdScaleMinus
  | WidgetConfigOccColdScalePlus
  | WidgetConfigOccLatPeakDegMinus
  | WidgetConfigOccLatPeakDegPlus
  | WidgetConfigOccLatWidthDegMinus
  | WidgetConfigOccLatWidthDegPlus
  | WidgetConfigSliceLatCenterMinus
  | WidgetConfigSliceLatCenterPlus
  | WidgetConfigSliceLonCenterMinus
  | WidgetConfigSliceLonCenterPlus
  | WidgetConfigLatitudeExponentMinus
  | WidgetConfigLatitudeExponentPlus
  | WidgetConfigPlateHeightCoolingMinus
  | WidgetConfigPlateHeightCoolingPlus
  | WidgetConfigTempNoiseScaleMinus
  | WidgetConfigTempNoiseScalePlus
  | WidgetConfigOceanModerationMinus
  | WidgetConfigOceanModerationPlus
  | WidgetConfigOceanModerateTempMinus
  | WidgetConfigOceanModerateTempPlus
  | WidgetConfigAlbedoSensitivityMinus
  | WidgetConfigAlbedoSensitivityPlus
  | WidgetConfigAlbedoReferenceMinus
  | WidgetConfigAlbedoReferencePlus
  | WidgetConfigMoistAdvectMinus
  | WidgetConfigMoistAdvectPlus
  | WidgetConfigMoistLocalMinus
  | WidgetConfigMoistLocalPlus
  | WidgetConfigMoistWindEvapScaleMinus
  | WidgetConfigMoistWindEvapScalePlus
  | WidgetConfigMoistEvapNoiseScaleMinus
  | WidgetConfigMoistEvapNoiseScalePlus
  | WidgetConfigMoistBareEvapFracMinus
  | WidgetConfigMoistBareEvapFracPlus
  | WidgetConfigMoistVegTranspFracMinus
  | WidgetConfigMoistVegTranspFracPlus
  | WidgetConfigMoistWindETScaleMinus
  | WidgetConfigMoistWindETScalePlus
  | WidgetConfigMoistCondensationRateMinus
  | WidgetConfigMoistCondensationRatePlus
  | WidgetConfigMoistRecycleRateMinus
  | WidgetConfigMoistRecycleRatePlus
  | WidgetConfigMoistITCZStrengthMinus
  | WidgetConfigMoistITCZStrengthPlus
  | WidgetConfigMoistITCZWidthMinus
  | WidgetConfigMoistITCZWidthPlus
  | WidgetConfigOrographicScaleMinus
  | WidgetConfigOrographicScalePlus
  | WidgetConfigOrographicStepMinus
  | WidgetConfigOrographicStepPlus
  | WidgetConfigCoastalIterationsMinus
  | WidgetConfigCoastalIterationsPlus
  | WidgetConfigCoastalDiffuseMinus
  | WidgetConfigCoastalDiffusePlus
  | WidgetConfigCoastalMoistureBoostMinus
  | WidgetConfigCoastalMoistureBoostPlus
  | WidgetConfigWindBeltStrengthMinus
  | WidgetConfigWindBeltStrengthPlus
  | WidgetConfigWindBeltHarmonicsMinus
  | WidgetConfigWindBeltHarmonicsPlus
  | WidgetConfigWindBeltBaseMinus
  | WidgetConfigWindBeltBasePlus
  | WidgetConfigWindBeltRangeMinus
  | WidgetConfigWindBeltRangePlus
  | WidgetConfigWindBeltSpeedScaleMinus
  | WidgetConfigWindBeltSpeedScalePlus
  | WidgetConfigBndLandRangeMinus
  | WidgetConfigBndLandRangePlus
  | WidgetConfigPiedmontSmoothMinus
  | WidgetConfigPiedmontSmoothPlus
  | WidgetConfigPiedmontSlopeMinMinus
  | WidgetConfigPiedmontSlopeMinPlus
  | WidgetConfigPiedmontSlopeMaxMinus
  | WidgetConfigPiedmontSlopeMaxPlus
  | WidgetConfigWindCoriolisDeflectionMinus
  | WidgetConfigWindCoriolisDeflectionPlus
  | WidgetConfigMoistMinVegFloorMinus
  | WidgetConfigMoistMinVegFloorPlus
  | WidgetConfigErosionHydraulicMinus
  | WidgetConfigErosionHydraulicPlus
  | WidgetConfigErosionThermalMinus
  | WidgetConfigErosionThermalPlus
  | WidgetConfigErosionRainRateMinus
  | WidgetConfigErosionRainRatePlus
  | WidgetConfigErosionTalusMinus
  | WidgetConfigErosionTalusPlus
  | WidgetConfigErosionMaxDropMinus
  | WidgetConfigErosionMaxDropPlus
  | WidgetConfigErosionHydDepositMinus
  | WidgetConfigErosionHydDepositPlus
  | WidgetConfigErosionDepositSlopeMinus
  | WidgetConfigErosionDepositSlopePlus
  | WidgetConfigErosionThermDepositMinus
  | WidgetConfigErosionThermDepositPlus
  | WidgetConfigErosionCoastZoneMinus
  | WidgetConfigErosionCoastZonePlus
  | WidgetConfigErosionCoastStrengthMinus
  | WidgetConfigErosionCoastStrengthPlus
  | WidgetConfigErosionCoastIterMinus
  | WidgetConfigErosionCoastIterPlus
  | WidgetConfigHypsometryEnabledMinus
  | WidgetConfigHypsometryEnabledPlus
  | WidgetConfigHypsometryLowlandExpMinus
  | WidgetConfigHypsometryLowlandExpPlus
  | WidgetConfigHypsometryHighlandExpMinus
  | WidgetConfigHypsometryHighlandExpPlus
  | WidgetConfigHypsometryPlateauBreakMinus
  | WidgetConfigHypsometryPlateauBreakPlus
  | WidgetConfigHypsometryOceanExpMinus
  | WidgetConfigHypsometryOceanExpPlus
  | WidgetConfigHypsometryCoastalRampWidthMinus
  | WidgetConfigHypsometryCoastalRampWidthPlus
  | WidgetConfigHypsometryCoastalRampStrMinus
  | WidgetConfigHypsometryCoastalRampStrPlus
  | WidgetConfigGlacierSnowTempMinus
  | WidgetConfigGlacierSnowTempPlus
  | WidgetConfigGlacierSnowRangeMinus
  | WidgetConfigGlacierSnowRangePlus
  | WidgetConfigGlacierMeltTempMinus
  | WidgetConfigGlacierMeltTempPlus
  | WidgetConfigGlacierMeltRateMinus
  | WidgetConfigGlacierMeltRatePlus
  | WidgetConfigGlacierAccumScaleMinus
  | WidgetConfigGlacierAccumScalePlus
  | WidgetConfigGlacierFlowItersMinus
  | WidgetConfigGlacierFlowItersPlus
  | WidgetConfigGlacierFlowRateMinus
  | WidgetConfigGlacierFlowRatePlus
  | WidgetConfigGlacierErosionScaleMinus
  | WidgetConfigGlacierErosionScalePlus
  | WidgetConfigGlacierCarveScaleMinus
  | WidgetConfigGlacierCarveScalePlus
  | WidgetConfigGlacierDepositScaleMinus
  | WidgetConfigGlacierDepositScalePlus
  | WidgetConfigVentDensityMinus
  | WidgetConfigVentDensityPlus
  | WidgetConfigVentThresholdMinus
  | WidgetConfigVentThresholdPlus
  | WidgetConfigHotspotScaleMinus
  | WidgetConfigHotspotScalePlus
  | WidgetConfigHotspotThresholdMinus
  | WidgetConfigHotspotThresholdPlus
  | WidgetConfigMagmaRechargeMinus
  | WidgetConfigMagmaRechargePlus
  | WidgetConfigLavaScaleMinus
  | WidgetConfigLavaScalePlus
  | WidgetConfigAshScaleMinus
  | WidgetConfigAshScalePlus
  | WidgetConfigVolcanicDepositScaleMinus
  | WidgetConfigVolcanicDepositScalePlus
  | WidgetConfigSoilMoistureThresholdMinus
  | WidgetConfigSoilMoistureThresholdPlus
  | WidgetConfigSoilHardnessThresholdMinus
  | WidgetConfigSoilHardnessThresholdPlus
  | WidgetConfigSoilFertilityMoistWeightMinus
  | WidgetConfigSoilFertilityMoistWeightPlus
  | WidgetConfigSoilFertilityDepthWeightMinus
  | WidgetConfigSoilFertilityDepthWeightPlus
  | WidgetConfigSinkBreachDepthMinus
  | WidgetConfigSinkBreachDepthPlus
  | WidgetConfigStreamPowerMaxErosionMinus
  | WidgetConfigStreamPowerMaxErosionPlus
  | WidgetConfigRiverCarveMaxDepthMinus
  | WidgetConfigRiverCarveMaxDepthPlus
  | WidgetConfigCoastalErodeStrengthMinus
  | WidgetConfigCoastalErodeStrengthPlus
  | WidgetConfigHydroHardnessWeightMinus
  | WidgetConfigHydroHardnessWeightPlus
  | WidgetConfigMinLakeSizeMinus
  | WidgetConfigMinLakeSizePlus
  | WidgetConfigInlandSeaMinSizeMinus
  | WidgetConfigInlandSeaMinSizePlus
  | WidgetConfigRoughnessScaleMinus
  | WidgetConfigRoughnessScalePlus
  | WidgetConfigHexSizeKmMinus
  | WidgetConfigHexSizeKmPlus
  | WidgetConfigGenScaleMinus
  | WidgetConfigGenScalePlus
  | WidgetConfigGenCoordScaleMinus
  | WidgetConfigGenCoordScalePlus
  | WidgetConfigGenOffsetXMinus
  | WidgetConfigGenOffsetXPlus
  | WidgetConfigGenOffsetYMinus
  | WidgetConfigGenOffsetYPlus
  | WidgetConfigGenFrequencyMinus
  | WidgetConfigGenFrequencyPlus
  | WidgetConfigGenOctavesMinus
  | WidgetConfigGenOctavesPlus
  | WidgetConfigGenLacunarityMinus
  | WidgetConfigGenLacunarityPlus
  | WidgetConfigGenGainMinus
  | WidgetConfigGenGainPlus
  | WidgetConfigGenWarpScaleMinus
  | WidgetConfigGenWarpScalePlus
  | WidgetConfigGenWarpStrengthMinus
  | WidgetConfigGenWarpStrengthPlus
  | WidgetConfigExtentXMinus
  | WidgetConfigExtentXPlus
  | WidgetConfigExtentYMinus
  | WidgetConfigExtentYPlus
  | WidgetConfigEdgeNorthMinus
  | WidgetConfigEdgeNorthPlus
  | WidgetConfigEdgeSouthMinus
  | WidgetConfigEdgeSouthPlus
  | WidgetConfigEdgeEastMinus
  | WidgetConfigEdgeEastPlus
  | WidgetConfigEdgeWestMinus
  | WidgetConfigEdgeWestPlus
  | WidgetConfigEdgeFalloffMinus
  | WidgetConfigEdgeFalloffPlus
  | WidgetConfigPlateSizeMinus
  | WidgetConfigPlateSizePlus
  | WidgetConfigUpliftMinus
  | WidgetConfigUpliftPlus
  | WidgetConfigRiftDepthMinus
  | WidgetConfigRiftDepthPlus
  | WidgetConfigDetailScaleMinus
  | WidgetConfigDetailScalePlus
  | WidgetConfigPlateSpeedMinus
  | WidgetConfigPlateSpeedPlus
  | WidgetConfigBoundarySharpnessMinus
  | WidgetConfigBoundarySharpnessPlus
  | WidgetConfigBoundaryNoiseScaleMinus
  | WidgetConfigBoundaryNoiseScalePlus
  | WidgetConfigBoundaryNoiseStrengthMinus
  | WidgetConfigBoundaryNoiseStrengthPlus
  | WidgetConfigBoundaryWarpOctavesMinus
  | WidgetConfigBoundaryWarpOctavesPlus
  | WidgetConfigBoundaryWarpLacunarityMinus
  | WidgetConfigBoundaryWarpLacunarityPlus
  | WidgetConfigBoundaryWarpGainMinus
  | WidgetConfigBoundaryWarpGainPlus
  | WidgetConfigPlateMergeScaleMinus
  | WidgetConfigPlateMergeScalePlus
  | WidgetConfigPlateMergeBiasMinus
  | WidgetConfigPlateMergeBiasPlus
  | WidgetConfigPlateDetailScaleMinus
  | WidgetConfigPlateDetailScalePlus
  | WidgetConfigPlateDetailStrengthMinus
  | WidgetConfigPlateDetailStrengthPlus
  | WidgetConfigPlateRidgeStrengthMinus
  | WidgetConfigPlateRidgeStrengthPlus
  | WidgetConfigPlateHeightBaseMinus
  | WidgetConfigPlateHeightBasePlus
  | WidgetConfigPlateHeightVarianceMinus
  | WidgetConfigPlateHeightVariancePlus
  | WidgetConfigPlateHardnessBaseMinus
  | WidgetConfigPlateHardnessBasePlus
  | WidgetConfigPlateHardnessVarianceMinus
  | WidgetConfigPlateHardnessVariancePlus
  | WidgetConfigTrenchDepthMinus
  | WidgetConfigTrenchDepthPlus
  | WidgetConfigRidgeHeightMinus
  | WidgetConfigRidgeHeightPlus
  | WidgetConfigPlateBiasStrengthMinus
  | WidgetConfigPlateBiasStrengthPlus
  | WidgetConfigPlateBiasCenterMinus
  | WidgetConfigPlateBiasCenterPlus
  | WidgetConfigPlateBiasEdgeMinus
  | WidgetConfigPlateBiasEdgePlus
  | WidgetConfigPlateBiasNorthMinus
  | WidgetConfigPlateBiasNorthPlus
  | WidgetConfigPlateBiasSouthMinus
  | WidgetConfigPlateBiasSouthPlus
  | WidgetConfigTfcCliffSlopeMinus
  | WidgetConfigTfcCliffSlopePlus
  | WidgetConfigTfcMountainSlopeMinus
  | WidgetConfigTfcMountainSlopePlus
  | WidgetConfigTfcMountainReliefMinus
  | WidgetConfigTfcMountainReliefPlus
  | WidgetConfigTfcHillSlopeMinus
  | WidgetConfigTfcHillSlopePlus
  | WidgetConfigTfcRollingSlopeMinus
  | WidgetConfigTfcRollingSlopePlus
  | WidgetConfigValleyCurvatureMinus
  | WidgetConfigValleyCurvaturePlus
  | WidgetConfigTfcElevGradientMinus
  | WidgetConfigTfcElevGradientPlus
  | WidgetConfigTfcPlateauMaxRelief2RingMinus
  | WidgetConfigTfcPlateauMaxRelief2RingPlus
  | WidgetConfigTfcPlateauMaxMicroReliefMinus
  | WidgetConfigTfcPlateauMaxMicroReliefPlus
  | WidgetConfigTfcRollingNearFactorMinus
  | WidgetConfigTfcRollingNearFactorPlus
  | WidgetConfigRockElevationThresholdMinus
  | WidgetConfigRockElevationThresholdPlus
  | WidgetConfigRockHardnessThresholdMinus
  | WidgetConfigRockHardnessThresholdPlus
  | WidgetConfigRockHardnessSecondaryMinus
  | WidgetConfigRockHardnessSecondaryPlus
  | WidgetViewElevation
  | WidgetViewBiome
  | WidgetViewClimate
  | WidgetViewWeather
  | WidgetViewMoisture
  | WidgetViewPrecip
  | WidgetViewVegetation
  | WidgetViewTerrainForm
  | WidgetViewPlateId
  | WidgetViewPlateBoundary
  | WidgetViewPlateHardness
  | WidgetViewPlateCrust
  | WidgetViewPlateAge
  | WidgetViewPlateHeight
  | WidgetViewPlateVelocity
  | WidgetViewOverlayPrev
  -- ^ Previous overlay in the overlay store.
  | WidgetViewOverlayNext
  -- ^ Next overlay in the overlay store.
  | WidgetViewFieldPrev
  -- ^ Previous field within the selected overlay.
  | WidgetViewFieldNext
  -- ^ Next field within the selected overlay.
  | WidgetLogDebug
  | WidgetLogInfo
  | WidgetLogWarn
  | WidgetLogError
  | WidgetLogHeader
  | WidgetMenuSave
  | WidgetMenuLoad
  | WidgetMenuExit
  | WidgetPresetSaveOk
  | WidgetPresetSaveCancel
  | WidgetPresetLoadOk
  | WidgetPresetLoadCancel
  | WidgetPresetLoadItem
  | WidgetWorldSaveOk
  | WidgetWorldSaveCancel
  | WidgetWorldLoadOk
  | WidgetWorldLoadCancel
  | WidgetWorldLoadItem
  | WidgetPipelineToggle !Text
  | WidgetPluginMoveUp !Text
  | WidgetPluginMoveDown !Text
  | WidgetPluginToggle !Text
  | WidgetPluginExpand !Text
  | WidgetPluginParamSlider !Text !Text
  | WidgetPluginParamCheck !Text !Text
  | WidgetSimTick
  | WidgetSimAutoTick
  -- Data browser (ConfigData tab)
  | WidgetConfigTabData
  | WidgetDataPluginSelect !Text
  | WidgetDataResourceSelect !Text !Text
  | WidgetDataPagePrev !Text !Text
  | WidgetDataPageNext !Text !Text
    -- Editor toolbar
  | WidgetEditorTool !Int
    -- ^ Tool button (0-indexed corresponding to 'EditorTool' enum order).
  | WidgetEditorRadiusMinus
  | WidgetEditorRadiusPlus
  | WidgetEditorClose
  deriving (Eq, Show)