module Actor.UI
  ( module Actor.UI.Setters
  , Ui
  , ConfigTab(..)
  , DataBrowserState(..)
  , emptyDataBrowserState
  , builtinStageRowCount
  , configRowCount
  , pluginRowIndex
  , pluginRowsWithParams
  , LeftTab(..)
  , UiMenuMode(..)
  , ViewMode(..)
  , allStandardViewModes
  , UiState(..)
  , emptyUiState
  , uiActorDef
  , UiSnapshotReply
  , requestUiSnapshot
  , getUiSnapshot
  , UiSnapshotRef
  , setUiSnapshotRef
  , readUiSnapshotRef
  , newUiSnapshotRef
  ) where

import Actor.UI.Setters
import Actor.UI.State
  ( ConfigTab(..)
  , DataBrowserState(..)
  , emptyDataBrowserState
  , LeftTab(..)
  , Ui
  , UiMenuMode(..)
  , UiSnapshotReply
  , UiSnapshotRef
  , UiState(..)
  , ViewMode(..)
  , allStandardViewModes
  , builtinStageRowCount
  , configRowCount
  , pluginRowIndex
  , pluginRowsWithParams
  , emptyUiState
  , getUiSnapshot
  , newUiSnapshotRef
  , readUiSnapshotRef
  , requestUiSnapshot
  , setUiSnapshotRef
  , uiActorDef
  )